create or replace view {DB_NAME}.DP_BIMO.DP_BIMO_DEVICE_REPLACEMENT_VW(
	TDE_DEVICE_REPLACEMENT_BK,
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	EVENT_TYPE,
	CHANNEL,
	PROBLEM_REPORTING_CHANNEL,
	DEVICE_TYPE_ORIGINAL,
	DEVICE_TYPE_NEW,
	DIAGNOSIS,
	TOTAL,
	RECORD_LOAD_DATETIME,
	_ETL_RUN_ID
) COMMENT='KAN-1 Data Product Device Replacement'
 as SELECT * FROM {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT;
ALTER VIEW {DB_NAME}.DP_BIMO.DP_BIMO_DEVICE_REPLACEMENT_VW SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
