-- Data Product View: DP_BIMO_DEVICE_REPLACEMENT_VW
CREATE VIEW IF NOT EXISTS {DB_NAME}.DP_BIMO.DP_BIMO_DEVICE_REPLACEMENT_VW AS
SELECT TDE_DEVICE_REPLACEMENT_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, EVENT_TYPE, CHANNEL, PROBLEM_REPORTING_CHANNEL, DEVICE_TYPE_ORIGINAL, DEVICE_TYPE_NEW, DIAGNOSIS, TOTAL
FROM {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT;
COMMENT ON VIEW {DB_NAME}.DP_BIMO.DP_BIMO_DEVICE_REPLACEMENT_VW IS 'KAN-1 Device Replacement data product view';
ALTER VIEW {DB_NAME}.DP_BIMO.DP_BIMO_DEVICE_REPLACEMENT_VW SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
