create or replace view {DB_NAME}.DP_BIMO.DP_CONSUMER_REGISTRATIONS_VW(
	TDE_CONSUMER_REGISTRATIONS_BK,
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	CHANNEL_NAME,
	SUB_CHANNEL,
	STORE_TYPE,
	IQOS_TYPE,
	VEEV_TYPE,
	TOTAL_REGISTRATIONS,
	RECORD_LOAD_DATETIME,
	_ETL_RUN_ID
) COMMENT='KAN-1 Data Product Consumer Registrations'
 as SELECT * FROM {DB_NAME}.PRESENTATION.P_T_CONSUMER_REGISTRATIONS;
ALTER VIEW {DB_NAME}.DP_BIMO.DP_CONSUMER_REGISTRATIONS_VW SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
