-- Staging: CONSUMER_REGISTRATIONS_SK
CREATE TABLE IF NOT EXISTS {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK (
  WEEK_END_DATE DATE,
  COUNTRY_CODE VARCHAR(255) NOT NULL,
  REGION VARCHAR(255),
  CHANNEL_NAME VARCHAR(255),
  SUB_CHANNEL VARCHAR(255),
  STORE_TYPE VARCHAR(255),
  IQOS_TYPE VARCHAR(255),
  VEEV_TYPE VARCHAR(255),
  TOTAL_REGISTRATIONS NUMBER(38,0) NOT NULL,
  TDE_CONSUMER_REGISTRATIONS_BK VARCHAR(64),
  SOURCE_FILE_NAME VARCHAR,
  SOURCE_LOADED_AT TIMESTAMP_NTZ
);
COMMENT ON TABLE {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK IS 'KAN-1 Consumer Registrations staging - Slovakia';
ALTER TABLE {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
