create or replace TABLE {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_EG (
	WEEK_END_DATE DATE,
	COUNTRY_CODE VARCHAR(255) NOT NULL,
	REGION VARCHAR(255),
	CHANNEL_NAME VARCHAR(255),
	SUB_CHANNEL VARCHAR(255),
	STORE_TYPE VARCHAR(255),
	IQOS_TYPE VARCHAR(255),
	VEEV_TYPE VARCHAR(255),
	TOTAL_REGISTRATIONS NUMBER(38,0) NOT NULL,
	TDE_CONSUMER_REGISTRATIONS_BK VARCHAR(64),
	SOURCE_FILE_NAME VARCHAR(16777216),
	SOURCE_LOADED_AT TIMESTAMP_NTZ(9)
)
COMMENT='KAN-1 staging Consumer Registrations EG';
ALTER TABLE {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_EG SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
