-- Staging: DEVICE_REPLACEMENT_SK
CREATE TABLE IF NOT EXISTS {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK (
  WEEK_END_DATE DATE,
  COUNTRY_CODE VARCHAR(255) NOT NULL,
  REGION VARCHAR(255),
  EVENT_TYPE VARCHAR(255),
  CHANNEL VARCHAR(255) NOT NULL,
  PROBLEM_REPORTING_CHANNEL VARCHAR(255) NOT NULL,
  DEVICE_TYPE_ORIGINAL VARCHAR(255),
  DEVICE_TYPE_NEW VARCHAR(255),
  DIAGNOSIS VARCHAR(255) NOT NULL,
  TOTAL NUMBER(20,2) NOT NULL,
  TDE_DEVICE_REPLACEMENT_BK VARCHAR(64),
  SOURCE_FILE_NAME VARCHAR,
  SOURCE_LOADED_AT TIMESTAMP_NTZ
);
COMMENT ON TABLE {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK IS 'KAN-1 Device Replacement staging - Slovakia';
ALTER TABLE {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
