create or replace TABLE {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ (
	WEEK_END_DATE DATE,
	COUNTRY_CODE VARCHAR(255) NOT NULL,
	REGION VARCHAR(255),
	EVENT_TYPE VARCHAR(255),
	CHANNEL VARCHAR(255) NOT NULL,
	PROBLEM_REPORTING_CHANNEL VARCHAR(255) NOT NULL,
	DEVICE_TYPE_ORIGINAL VARCHAR(255),
	DEVICE_TYPE_NEW VARCHAR(255),
	DIAGNOSIS VARCHAR(255) NOT NULL,
	TOTAL NUMBER(20,2) NOT NULL,
	TDE_DEVICE_REPLACEMENT_BK VARCHAR(64),
	SOURCE_FILE_NAME VARCHAR(16777216),
	SOURCE_LOADED_AT TIMESTAMP_NTZ(9)
) WITH TAG ({DB_NAME}.PMI_AGENT.BIONIC_PMI_POC='KAN-1')
COMMENT='KAN-1 staging Device Replacement CZ'
;
