-- Secure View: CONSUMER_REGISTRATIONS_CZ_SV
CREATE SECURE VIEW IF NOT EXISTS {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ_SV AS
SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS
FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ_SV IS 'KAN-1 Consumer Registrations secure view - Czech Republic';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
