create or replace secure view {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK_SV(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	CHANNEL_NAME,
	SUB_CHANNEL,
	STORE_TYPE,
	IQOS_TYPE,
	VEEV_TYPE,
	TOTAL_REGISTRATIONS,
	TDE_CONSUMER_REGISTRATIONS_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) COMMENT='KAN-1 secure view Consumer Registrations SK'
 as SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK;
ALTER VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
