CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV IS 'KAN-1 secure view Consumer Registrations DE';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
