create or replace secure view {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	CHANNEL_NAME,
	SUB_CHANNEL,
	STORE_TYPE,
	IQOS_TYPE,
	VEEV_TYPE,
	TOTAL_REGISTRATIONS,
	TDE_CONSUMER_REGISTRATIONS_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) as SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE;
