CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA_SV IS 'KAN-1 secure view Consumer Registrations CA';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
