-- Secure View: DEVICE_REPLACEMENT_EG_SV
CREATE SECURE VIEW IF NOT EXISTS {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV AS
SELECT TDE_DEVICE_REPLACEMENT_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, EVENT_TYPE, CHANNEL, PROBLEM_REPORTING_CHANNEL, DEVICE_TYPE_ORIGINAL, DEVICE_TYPE_NEW, DIAGNOSIS, TOTAL
FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV IS 'KAN-1 Device Replacement secure view - Egypt';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
