CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV IS 'KAN-1 secure view Device Replacement DE';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
