create or replace secure view {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	EVENT_TYPE,
	CHANNEL,
	PROBLEM_REPORTING_CHANNEL,
	DEVICE_TYPE_ORIGINAL,
	DEVICE_TYPE_NEW,
	DIAGNOSIS,
	TOTAL,
	TDE_DEVICE_REPLACEMENT_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) WITH TAG ({DB_NAME}.PMI_AGENT.BIONIC_PMI_POC='KAN-1')
 COMMENT='KAN-1 staging secure view Device Replacement SK'
 as SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK;