CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ_SV IS 'KAN-1 secure view Device Replacement CZ';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
