CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV IS 'KAN-1 secure view Device Replacement EG';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
