create or replace secure view {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	EVENT_TYPE,
	CHANNEL,
	PROBLEM_REPORTING_CHANNEL,
	DEVICE_TYPE_ORIGINAL,
	DEVICE_TYPE_NEW,
	DIAGNOSIS,
	TOTAL,
	TDE_DEVICE_REPLACEMENT_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) as SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE;
