CREATE OR REPLACE SECURE VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV AS SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK;
COMMENT ON VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV IS 'KAN-1 secure view Device Replacement SK';
ALTER VIEW {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
