create or replace view CONSUMER_REGISTRATIONS_VW_INT(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	CHANNEL_NAME,
	SUB_CHANNEL,
	STORE_TYPE,
	IQOS_TYPE,
	VEEV_TYPE,
	TOTAL_REGISTRATIONS,
	TDE_CONSUMER_REGISTRATIONS_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) WITH TAG ({DB_NAME}.PMI_AGENT.BIONIC_PMI_POC='KAN-1')
 COMMENT='KAN-1 Integration UNION ALL Consumer Registrations'
 as SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_EG_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ_SV;