CREATE OR REPLACE VIEW {DB_NAME}.BIMO_INT.CONSUMER_REGISTRATIONS_VW_INT AS
SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS, SOURCE_FILE_NAME, SOURCE_LOADED_AT FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CA_SV
UNION ALL SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS, SOURCE_FILE_NAME, SOURCE_LOADED_AT FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_CZ_SV
UNION ALL SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS, SOURCE_FILE_NAME, SOURCE_LOADED_AT FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_DE_SV
UNION ALL SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS, SOURCE_FILE_NAME, SOURCE_LOADED_AT FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_EG_SV
UNION ALL SELECT TDE_CONSUMER_REGISTRATIONS_BK, WEEK_END_DATE, COUNTRY_CODE, REGION, CHANNEL_NAME, SUB_CHANNEL, STORE_TYPE, IQOS_TYPE, VEEV_TYPE, TOTAL_REGISTRATIONS, SOURCE_FILE_NAME, SOURCE_LOADED_AT FROM {DB_NAME}.SHR_SCHEMA.CONSUMER_REGISTRATIONS_SK_SV;
COMMENT ON VIEW {DB_NAME}.BIMO_INT.CONSUMER_REGISTRATIONS_VW_INT IS 'KAN-1 Consumer Registrations integration UNION ALL view';
ALTER VIEW {DB_NAME}.BIMO_INT.CONSUMER_REGISTRATIONS_VW_INT SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
