-- Integration View: DEVICE_REPLACEMENT_VW_INT
CREATE VIEW IF NOT EXISTS {DB_NAME}.BIMO_INT.DEVICE_REPLACEMENT_VW_INT AS
SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CA_SV
UNION ALL
SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ_SV
UNION ALL
SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV
UNION ALL
SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV
UNION ALL
SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV;
COMMENT ON VIEW {DB_NAME}.BIMO_INT.DEVICE_REPLACEMENT_VW_INT IS 'KAN-1 Device Replacement integration view - UNION ALL of country secure views';
ALTER VIEW {DB_NAME}.BIMO_INT.DEVICE_REPLACEMENT_VW_INT SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
