create or replace view {DB_NAME}.BIMO_INT.DEVICE_REPLACEMENT_VW_INT(
	WEEK_END_DATE,
	COUNTRY_CODE,
	REGION,
	EVENT_TYPE,
	CHANNEL,
	PROBLEM_REPORTING_CHANNEL,
	DEVICE_TYPE_ORIGINAL,
	DEVICE_TYPE_NEW,
	DIAGNOSIS,
	TOTAL,
	TDE_DEVICE_REPLACEMENT_BK,
	SOURCE_FILE_NAME,
	SOURCE_LOADED_AT
) COMMENT='KAN-1 Integration UNION ALL DEVICE_REPLACEMENT'
 as SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CZ_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_DE_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_EG_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_SK_SV UNION ALL SELECT * FROM {DB_NAME}.SHR_SCHEMA.DEVICE_REPLACEMENT_CA_SV;
