-- Presentation: P_T_DEVICE_REPLACEMENT
CREATE TABLE IF NOT EXISTS {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT (
  TDE_DEVICE_REPLACEMENT_BK VARCHAR(64),
  WEEK_END_DATE DATE,
  COUNTRY_CODE VARCHAR(255),
  REGION VARCHAR(255),
  EVENT_TYPE VARCHAR(255),
  CHANNEL VARCHAR(255),
  PROBLEM_REPORTING_CHANNEL VARCHAR(255),
  DEVICE_TYPE_ORIGINAL VARCHAR(255),
  DEVICE_TYPE_NEW VARCHAR(255),
  DIAGNOSIS VARCHAR(255),
  TOTAL NUMBER(20,2),
  RECORD_LOAD_DATETIME TIMESTAMP_NTZ,
  _ETL_RUN_ID NUMBER(38,0)
);
COMMENT ON TABLE {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT IS 'KAN-1 Device Replacement presentation table';
ALTER TABLE {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT SET TAG {DB_NAME}.PMI_AGENT.BIONIC_PMI_POC = 'KAN-1';
