create or replace TABLE {DB_NAME}.PRESENTATION.P_T_DEVICE_REPLACEMENT (
	TDE_DEVICE_REPLACEMENT_BK VARCHAR(64),
	WEEK_END_DATE DATE,
	COUNTRY_CODE VARCHAR(255),
	REGION VARCHAR(255),
	EVENT_TYPE VARCHAR(255),
	CHANNEL VARCHAR(255),
	PROBLEM_REPORTING_CHANNEL VARCHAR(255),
	DEVICE_TYPE_ORIGINAL VARCHAR(255),
	DEVICE_TYPE_NEW VARCHAR(255),
	DIAGNOSIS VARCHAR(255),
	TOTAL NUMBER(20,2),
	RECORD_LOAD_DATETIME TIMESTAMP_NTZ(9),
	_ETL_RUN_ID NUMBER(38,0)
) WITH TAG ({DB_NAME}.PMI_AGENT.BIONIC_PMI_POC='KAN-1')
COMMENT='KAN-1 Presentation Device Replacement'
;
