create or replace TABLE {DB_NAME}.PRESENTATION.P_T_CONSUMER_REGISTRATIONS (
	TDE_CONSUMER_REGISTRATIONS_BK VARCHAR(64),
	WEEK_END_DATE DATE,
	COUNTRY_CODE VARCHAR(255),
	REGION VARCHAR(255),
	CHANNEL_NAME VARCHAR(255),
	SUB_CHANNEL VARCHAR(255),
	STORE_TYPE VARCHAR(255),
	IQOS_TYPE VARCHAR(255),
	VEEV_TYPE VARCHAR(255),
	TOTAL_REGISTRATIONS NUMBER(38,0),
	RECORD_LOAD_DATETIME TIMESTAMP_NTZ(9),
	_ETL_RUN_ID NUMBER(38,0)
) WITH TAG ({DB_NAME}.PMI_AGENT.BIONIC_PMI_POC='KAN-1')
COMMENT='KAN-1 Presentation Consumer Registrations'
;
